### ISSUE TITLE
capturing large scene

### ISSUE THREAD

**Issue by petrasvestartas** [stgeorges/gismo#6] opened 2017-10-06 18:05 UTC
Hi 

I would like to capture mesh of large scene 20 km radius.
I do not need that model precise just low poly.

Would it be possible to get example that runs faster than analyze_terain.gh
I just changed from 600 meters to 6000 and it already runs for half an hour in gh...
no result. For 600 it worked well.

I need low res terrain only.

**Comment by stgeorges** [comment] 2017-10-06 20:00
Hi @petrasvestartas ,

You would like to generate a terrain, and then additionally perform an analysis on it?
Which one particularly?
In general, terrain analysis from 6 to 9 can be a lot more time consuming than others.

Also, try setting your "Terrain Generator's" _source__ input to 2. This source is actually made for underwater terrain but it also contains above water one, but in quite coarse resolution.

Please feel free, to report back, or ask anything else (I closed it by accident. Sorry about that).

**Comment by petrasvestartas** [comment] 2017-10-06 20:42
I changed output to mesh and countours to 0, it took long but did the job. It is cool.

Is it possible to get more low poly mesh?

Second question is possible to apply google map texture for the terrain?

**Comment by stgeorges** [comment] 2017-10-07 06:03
Hi @petrasvestartas ,
Glad you found another enhancement!
When trying to get even more low poly mesh, did you set the _source__ input of the "Terrain Generator" component to 2?
Can you please attach your .gh file?

For the application of satellite imagery to Gismo terrain mesh, check [this .gh definition](http://www.grasshopper3d.com/xn/detail/2985220:Comment:1800481) from forum. In order for it to work, it requires [Human](http://www.food4rhino.com/app/human) plugin installed.

**Comment by petrasvestartas** [comment] 2017-10-07 11:27
<img width="1440" alt="sdas" src="https://user-images.githubusercontent.com/18013985/31307315-3b604c4e-ab62-11e7-8bf7-bbab2d23ad20.png">



Any ideas? image

**Comment by petrasvestartas** [comment] 2017-10-07 12:19
It would be nice if terrain mapping would be part of gizmo, those multiple errors in ladybug and slow performance really not nice.... I try to go manually make screenshot in google earth...

but if you have solution for getting texture it would be much appreciated, and I hope it is not tilling with google earth icon that needs photo-shopping...

**Comment by stgeorges** [comment] 2017-10-07 12:19
Hi Petras,
Gismo currently does not have satellite imagery, so the [.gh definition](http://www.grasshopper3d.com/xn/detail/2985220:Comment:1800481) that I mentioned in my previous post actually uses Ladybug "Terrain Generator" component. That's the one you see in a screenshot you posted.
The error "out of range" typically happens when the access to Google Maps API fails. The reason for this is unknown (at least to me), but it probably has something to do with the fact that the service is free, so at particular moment there may be limited number of allowed "calls" to the API. I may be wrong on this, though.
The solution to this problem is actually simple: you just wait a couple of seconds, and set the "_runIt" input of the Ladybug "Terrain Generator" component to False, and then to True.
Have in mind that, in case of large _radius__ values, you may not be able to create the terrain with Ladybug "Terrain Generator" component, as call to Google Maps API may fail, due to it being limited to certain number of points (the terrain will we consisted of a grid of points, each representing elevation).

edit: I posted a reply literally 10 seconds after you last one.
When it comes to satellite imagery: we do not have an open source and free one at the moment, which can be queried. At least not to my knowledge, if I am wrong, please post a link.
There have been [requests similar](http://www.grasshopper3d.com/group/gismo/forum/topics/os-maps-and-esri-open-source-d-data) to yours on forum, but the issue is that they require their satellite data to be used as a background layer for mapping vector features (as openstreetmap data), and Gismo at the moment does not have this functionality.
So I can come up with free and open source solution from landsat satellite imagery which do not have any icon nor logo on them. The problem is that, they would have to be [manually downloaded](https://www.youtube.com/watch?v=c_nCoaL0bVs) first, then the folder with their images would have to be references to Gismo component, and Gismo component will then extract the satellite image for particular __location_ and __radius_. If this is not too tiresome for you, I may be able to come up with something.

**Comment by petrasvestartas** [comment] 2017-10-07 12:26
that really sucks, as it is tiling failure that does not allow zoom out screengrabs...

**Closed as completed** 2017-10-07 12:36 UTC
